name: Publish Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Change package version
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :updateVersion
          
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
          
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishAllPublicationsToGitHubPackagesRepository
        env:
          TOKEN: ${{ secrets.AUTO_TOKEN }}
          USERNAME: ${{ secrets.AUTO_USERNAME }}

      - name: Setup NPM
        run: npm config set //npm.pkg.github.com/:_authToken=$token
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup package name
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: prepareForGithubNpmPublish

      - name: Publish to npm
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishToNpm

      - name: Setup package name for legacy
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: prepareForGithubNpmPublishLegacy

      - name: Publish legacy to npm
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishToNpm
